#!/usr/bin/env bash
# =============================================================================
# Legafy AI — sandbox
#
# Stands up an isolated instance for testing: its own generated/ directory, its
# own tenant registry, its own minted token, and the offline provider so no
# model API key is needed and nothing leaves the machine.
#
# Why a sandbox rather than "just run it":
#   * The dev bootstrap token (akridion_dev_99x) is a shared secret in the
#     source tree. Handing it to a tester teaches them a habit we do not want,
#     and it is refused in production anyway — so a sandbox that uses it is not
#     testing the path a real tenant takes.
#   * A tester's audit vault must not mix with yours. The vault is hash-chained
#     and append-only; two people writing to one file makes the chain a shared
#     fate, and a reset by one destroys the other's record.
#   * Resetting must be safe. Everything the sandbox writes lives under
#     sandbox/, so `--reset` cannot touch a real vault by accident.
#
#   ./scripts/sandbox.sh              # create (or show) the sandbox
#   ./scripts/sandbox.sh --reset      # wipe it and mint a fresh token
#   ./scripts/sandbox.sh --tier PREMIUM_HOSTED   # a token that can draft too
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
SANDBOX="${REPO_ROOT}/sandbox"
TIER="DEVELOPER_FREE"
RESET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset) RESET=1; shift ;;
    --tier)  TIER="${2:?--tier needs a value}"; shift 2 ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

if [[ -t 1 ]]; then
  B=$'\033[1m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[0m'
else
  B=""; G=""; Y=""; R=""
fi

case "$TIER" in
  DEVELOPER_FREE) SCOPES='["audit"]' ;;
  PREMIUM_HOSTED) SCOPES='["audit","generate"]' ;;
  ENTERPRISE_B2B) SCOPES='["audit","generate","review"]' ;;
  *) echo "unknown tier: $TIER" >&2; exit 2 ;;
esac

if [[ $RESET -eq 1 ]]; then
  echo "${Y}Wiping ${SANDBOX}${R}"
  rm -rf "$SANDBOX"
fi

# No Python required: the sandbox must work on a machine that only has Docker.
rand_hex() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 24
  else head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then printf %s "$1" | sha256sum | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then printf %s "$1" | shasum -a 256 | cut -d' ' -f1
  else echo "Need sha256sum, shasum or openssl to mint a token." >&2; exit 1; fi
}
plus_30_days() {
  date -u -d "+30 days" +%Y-%m-%d 2>/dev/null || date -u -v+30d +%Y-%m-%d
}
PY="${REPO_ROOT}/.venv/bin/python"   # only used in the printed instructions
[[ -x "$PY" ]] || PY="$(command -v python3 || echo python3)"

if [[ -f "${SANDBOX}/token.txt" ]]; then
  TOKEN="$(cat "${SANDBOX}/token.txt")"
  echo "${Y}Sandbox already exists.${R} Use --reset to mint a fresh token."
else
  mkdir -p "${SANDBOX}/generated"
  chmod 700 "${SANDBOX}/generated"
  # Not $RANDOM: this token is handed to a person and gates a paid tool.
  TOKEN="legafy_sbx_$(rand_hex)"
  DIGEST="$(sha256_of "$TOKEN")"
  EXPIRES="$(plus_30_days)"

  cat > "${SANDBOX}/license_registry.json" <<JSON
{
  "_README": "Sandbox tenant registry. Generated by scripts/sandbox.sh — do not commit. The raw token is stored beside this file in token.txt for your convenience ONLY because this is a sandbox; a production registry holds the digest and nothing else.",
  "sandbox-tester": {
    "organization_name": "Legafy Sandbox Tester",
    "tier": "${TIER}",
    "token_sha256": "${DIGEST}",
    "expires_on": "${EXPIRES}",
    "rate_limit_per_minute": 30,
    "monthly_quota": 2000,
    "scopes": ${SCOPES}
  }
}
JSON
  printf %s "$TOKEN" > "${SANDBOX}/token.txt"
  chmod 600 "${SANDBOX}/token.txt" "${SANDBOX}/license_registry.json"

  cat > "${SANDBOX}/.env.sandbox" <<ENV
# Sourced by scripts/sandbox.sh. Isolated from your real .env on purpose.
LEGAFY_ENV=development
LEGAFY_LOG_LEVEL=DEBUG
LEGAFY_PROVIDER_CHAIN=offline
LEGAFY_BOOTSTRAP_TOKENS_ENABLED=false
LEGAFY_LICENSE_REGISTRY_PATH=sandbox/license_registry.json
LEGAFY_GENERATED_DIR=sandbox/generated
LEGAFY_AUDIT_VAULT_PATH=sandbox/generated/akrigon_audit_vault.json
LEGAFY_TELEMETRY_SALT=sandbox-salt-not-for-production
ENV
  echo "${G}Sandbox created.${R}"
fi

# Bootstrap tokens are OFF in the sandbox, so this token is the only way in —
# which is the point: it tests the path a real tenant actually takes.
cat <<INFO

${B}Legafy sandbox${R}
  tier            ${TIER}
  scopes          ${SCOPES}
  registry        sandbox/license_registry.json
  vault + output  sandbox/generated/   (separate from your real one)
  provider        offline (no model API key needed, nothing leaves this machine)

${B}Token${R} — treat it like a password, it expires in 30 days:
  ${TOKEN}

${B}Start it — local${R}
  set -a; source sandbox/.env.sandbox; set +a
  .venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8000

${B}Start it — Docker${R} (no Python on this machine needed)
  docker compose -f docker-compose.yml -f docker-compose.sandbox.yml up -d api
  docker compose logs -f api

${B}Check it${R}
  curl -s localhost:8000/healthz
  curl -s -X POST localhost:8000/api/v1/audit \\
    -H "Authorization: Bearer ${TOKEN}" -H 'Content-Type: application/json' \\
    -d '{"business_concept":"A marketplace for local tutors","industry_vertical":"marketplace","state_location":"Telangana","activity_flags":["operates_digital_service"]}'

${B}Claude Desktop${R} — ~/Library/Application Support/Claude/claude_desktop_config.json
{
  "mcpServers": {
    "legafy-sandbox": {
      "command": "${REPO_ROOT}/.venv/bin/python",
      "args": ["-m", "app.mcp.server"],
      "cwd": "${REPO_ROOT}",
      "env": {
        "LEGAFY_MCP_MODE": "local",
        "LEGAFY_ENV": "development",
        "LEGAFY_LOG_LEVEL": "DEBUG",
        "LEGAFY_PROVIDER_CHAIN": "offline",
        "LEGAFY_BOOTSTRAP_TOKENS_ENABLED": "false",
        "LEGAFY_LICENSE_REGISTRY_PATH": "sandbox/license_registry.json",
        "LEGAFY_GENERATED_DIR": "sandbox/generated",
        "LEGAFY_AUDIT_VAULT_PATH": "sandbox/generated/akrigon_audit_vault.json",
        "LEGAFY_TELEMETRY_SALT": "sandbox-salt-not-for-production",
        "LEGAFY_API_TOKEN": "${TOKEN}"
      }
    }
  }
}

${B}Verify what happened${R}
  wc -l sandbox/generated/akrigon_audit_vault.json    # one line per call
  tail -1 sandbox/generated/akrigon_audit_vault.json | ${PY} -m json.tool

Full walkthrough, including how to share this with a remote tester:
  docs/TESTING_PLAYBOOK.md
INFO
